[build-system]
requires = [
    "setuptools>=42,<58",  # pyhash-0.9.3 fails to install with setuptools-58.2.0 when using Python 3.7
    "wheel",
    "setuptools_scm[toml]>=3.4"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
